version: '3.9'
services:
  librarian:
    container_name: Librarian
    pull_policy: build
    build: https://github.com/BrackeysBot/Librarian.git#main
    volumes:
      - type: bind
        source: /var/log/brackeysbot/librarian
        target: /app/logs
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
